[package]
name = "gse_c_rust_api"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.147"
dvb_gse_rust = { git = "https://github.com/viveris/dvb_gse_rust.git", tag = "v0.8.0" }

[lib]
name = "gse_rust_c_api"
crate-type = ["cdylib", "staticlib"] # Creates dynamic and static C lib
